### ISSUE TITLE
Missing sockets.so php extension

### ISSUE THREAD

**Issue by boardwarp** [linuxserver/docker-rutorrent#110]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Debian Jessie 9.4

```
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    ports:
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped
    volumes:
      - /home/boardwarp/.docker/rutorrent:/config
      - /home/boardwarp/downloads:/downloads
    environment:
      - PUID=1001
      - PGID=999
```

Hello! I'm trying to configure the auto-dl plugin with this rutorrent container. Initially it's missing the sockets extension, but running the `apk add php7-sockets` command inside the container. Any chance this could be added to the image to enhance compatibility for rutorrent plugins?
