### ISSUE TITLE
rtorrent SCGI port or socket

### ISSUE THREAD

**Issue by zanloy** [linuxserver/docker-rutorrent#122]
I need the host system and possibly other docker containers to access the scgi port of rtorrent. This allows other containers (eg: radarr, sickchill) to add torrents. But even though the documentation says to expose port 5000, when you look at the rtorrent.rc file, it's using a socket and not port 5000. Unfortunately I can not enable the port in the config (it's commented out by default) because it fails saying that "SCGI already enabled." This seems to be a limitation of rtorrent. You can either use a socket or the port but not both.

So the solution to this is either
a) export the socket file in /config instead of /run/php/.rtorrent.sock
b) change to using tcp port and update rutorrent's config.php to point to tcp port instead of socket.

I want to know what the best way to move forward is. I do not want to make edits inside the container because that breaks my ability to bring down updates from upstream.

**Comment by zanloy** [comment]
I just realized that I can edit the rutorrent config.php outside the container so I can fix that. But you should probably just remove the references to exposing port 5000 if you don't use it anyways.

**Comment by flatline-studios** [comment]
Just wasted several hours discovering this the hard way... Thanks for posting this, or I might still of been wasting time.

**UPDATE**: Maybe just a note on the readme to mention that there's a limitation in rTorrent to only allow either the socket or the SCGI, and that the shipped/default rtorrent.rc file uses the socket option? That's why the `scgi_port` line is commented out.

**Comment by adamwinn** [comment]
@zanloy or @flatline-studios Can either of you share you `rtorrent.rc` and `config.php` config?  I can't seem to get mine to work.

**Comment by flatline-studios** [comment]
> @zanloy or @flatline-studios Can either of you share you `rtorrent.rc` and `config.php` config? I can't seem to get mine to work.

Hi, my issue was different to this one... What is it that you're trying to do exactly?

Quick bit of guidance... rTorrent itself uses either:
- A `socket` (which is a *file* that acts as a kind of hub that services can communicate through)
- An `scgi` service (which is a *protocol* [or language of sorts] that related services have agreed upon, and can both *speak*)

This docker image uses the `socket` approach in its default `rtorrent.rc`, and apparently rTorrent can only use one of these communication mechanisms at a time.

**Comment by zanloy** [comment]
So I went with a different route to get all the apps to talk to each other. You can't expose the socket so I setup rtorrent to use 5000/tcp. Then I created a docker network called 'backend' and added all my containers that needed to talk to each other on that network. Because by default docker-compose creates isolated networks for each compose file. This means all containers in a single docker-compose.yml can talk to each other using their hostnames. Another gotcha is that docker has a 'default' network that everything is added to if a custom network is not defined but that network *does not* allow containers to talk to each other. You have to create the custom network. Here's an example:

rutorrent/docker-compose.yml:
```
---
version: "2"

services:
  rutorrent:
    image: linuxserver/rutorrent:latest
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - /home/zan/downloads:/downloads
    ports:
      - "6980:80"
      - "51413:51413"
      - "6881:6881/udp"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    external: true
```

sickchill/docker-compose.yml:
```
---
version: "3"

services:
  sickchill:
    image: linuxserver/sickchill:latest
    container_name: sickchill
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /netshare/downloads:/downloads
      - /netshare/videos/tv:/tv
      - /netshare/videos/kids/tv:/kids-tv
    ports:
      - "7280:8081"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    external: true
```

This is not a current working config though for rtorrent because I actually moved all my stuff like sickchill/radarr/etc to use usenet instead of torrents and sabnzbd to download files. But when it was working, you could then just use http://rutorrent:5000/RPC2 as your url for the configurations and it'd talk to the correct container.
