### ISSUE TITLE
Move based on label

### ISSUE THREAD

**Issue by h-wb** [linuxserver/docker-rutorrent#130]
**Host OS** : RancherOS
**Docker compose**  :
```
 rutorrent:
    image: "linuxserver/rutorrent"
    container_name: "rutorrent"
    tty: true
    volumes:
      - ${USERDIR}/docker/rutorrent:/config
      - ${USERDIR}/docker/rutorrent/themes:/app/rutorrent/plugins/theme/themes
      - ${MEDIADIR}:/data
      - ${USERDIR}/docker/shared:/shared
    ports:
      - 9187:80
      - 51413:51413
      - 5000:5000
      - 6881:6881/udp
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.frontend=rutorrent"
      - "traefik.domain=rutorrent.${DOMAINNAME}"
      - "traefik.port=9443"
      - "traefik.frontend.rule=Host:rutorrent.${DOMAINNAME}"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.auth.forward.address=http://organizr/api/?v1/auth&group=0"
    depends_on:
      - traefik
      - organizr
```
**Docker log** : Nothing anormal with log, everything is running fine

-------------------------

Hello, 

I want to move my torrents based on label so in my torrent.rc I wrote these lines :

```
method.insert = d.get_finished_dir, simple, "cat=/data/downloads/complete/,$d.custom1="
method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="
```

The path from the first line is the only thing I changed from the code shown here : 
https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#move-completed-torrents-to-a-fixed-location

Unfortunately, it is not working. Theses lines should be working as I already tried on different rutorrent container, even another one based on this one (https://github.com/romancin/rutorrent-flood-docker) 

I saw an issue like that was already mentioned here : [linuxserver/docker-rutorrent#88](https://github.com/linuxserver/docker-rutorrent/issues/88) but It was not really resolved. I think my rtorrent.rc is not ignored because I changed some parameters and it's shown on rutorrent.

I don't know if I'm doing something wrong with path or something like that, so do you mind helping me ?

Thank you.
