### ISSUE TITLE
Advanced > CA certificate and path settings are not persisted in /config

### ISSUE THREAD

**Issue by nappy** [linuxserver/docker-rutorrent#168]
In general I am not able to persist custom CA configuration.

## Expected Behavior
When I change CA certificate or path inside the UI, that change should be persisted in /config or additional required mounts points should be documented

## Current Behavior
I need to configure after each container start

## Steps to Reproduce
1. Start container
2. Start a torrent using an untrusted announce URL and get it erroring
3. Change advanced values to include custom CA cert (pem)
4. Update Tracker (should resolve the error)
5. Restart container

## Environment
**OS:** debian
**CPU architecture:** x86_64
**How docker service was installed:**      
Though repository, docker-compose prebuilt binary

## Command used to create docker container (run/create/compose/screenshot)
```
rutorrent:
        image: linuxserver/rutorrent:v3.10-ls90
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
        ports:
            - 51413:51413
            - 51413:51413/udp
        volumes:
            - ./certs:/certs
            - rutorrent_config:/config
            - rutorrent_downloads:/downloads
```
