### ISSUE TITLE
Big CPU spikes every 15 seconds

### ISSUE THREAD

**Issue by bxkx** [linuxserver/docker-rutorrent#185]
------------------------------

## Expected Behavior
No huge CPU spikes.

## Current Behavior
Overall CPU usage spikes up to 30 - 35% from 5 - 10% every 15 seconds exactly.

## Steps to Reproduce
Just download and run the docker.

I've tested rtorrent+rutorrent outside of a Docker container and while there is something happening every 15 seconds, it's just a little bump and barely noticeable. 
However, using the Docker container causes a significant spike.

Here's a Netdata screenshot of the overall CPU usage:
![image](https://user-images.githubusercontent.com/15363535/104016308-611b2a00-51b6-11eb-9381-8ab7db2ea5c2.png)

And the container:
![image](https://user-images.githubusercontent.com/15363535/104016693-1b129600-51b7-11eb-99ef-f28e12ccf8c4.png)

It also coincides with the memory page fault, if that's helpful.

## Environment
KVM VPS, 1 Core, 1GB RAM
**OS:** Debian 10
**CPU architecture:** x86_64
**How docker service was installed:** Docker repo, Docker version 20.10.2 (same with 18.09.1 from the Debian repos)

## Command used to create docker container (run/create/compose/screenshot)
```
rutorrent:
        image: ghcr.io/linuxserver/rutorrent
        container_name: rutorrent
        environment:
           - PUID=1000
           - PGID=1000
        volumes:
           - /opt/docker/rutorrent/config/:/config
           - /media/torrent/downloads/:/downloads
        ports:
           - 80:80
           - 5000:5000
           - 51413:51413
           - 51413:51413/udp
           - 6881:6881/udp
        restart: unless-stopped
```

## Docker logs
```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 10-nginx-fix: executing... 
Current version detected.
[cont-init.d] 10-nginx-fix: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

I also checked the rtorrent.log and rutorrent.log which are both empty.
