### ISSUE TITLE
rTorrent user can't access "id" program. Some functionality will be unavailable.

### ISSUE THREAD

**Issue by the-lazy-fox** [linuxserver/docker-rutorrent#189]
## Situation
I have updated my container more than a week ago and since this moment, I cannot make most of the rutorrent feature to work correctly. It seems to have a cascade of dependencies not matching anymore.
![image](https://user-images.githubusercontent.com/35723598/109969323-0e607900-7cf4-11eb-9d03-c0fceb71967d.png)
My compose and my docker environment didn't change at all in the meanwhile.
Using the latest as of today.

Thanks for your help

## Environment
**OS:** Docker v18.09.8 on a Synology DS916+
**CPU architecture:** x86_64
**How docker service was installed:**
Official Synology Package

## Command used to create docker container (run/create/compose/screenshot)
```
rutorrent:
    container_name: rutorrent-default
    image: ghcr.io/linuxserver/rutorrent:latest
    restart: unless-stopped
    depends_on:
     - vpn
    network_mode: "service:vpn"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /volume1/media/Downloads:/downloads/completed
      - /volumeSATA/satashare/cache-downloads:/downloads/incoming
      - /volume1/docker/rutorrent-default/watched:/downloads/watched
      - /volume1/docker/rutorrent-default/config:/config
      - /volume1/docker/rutorrent/config/packages.sh:/etc/cont-init.d/90-customconfig:ro
      - /volume1/docker/rutorrent/scripts:/scripts
      - /volume1/docker/rutorrent/plugins/tracklabels/labels:/app/rutorrent/plugins/tracklabels/labels:ro
      - /volume1/docker/rutorrent/plugins/tracklabels/trackers:/app/rutorrent/plugins/tracklabels/trackers:ro
      - /volume1/docker/rutorrent/themes:/app/rutorrent/plugins/theme/themes
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80/ || exit 1"]  
      interval: 1m30s
      timeout: 10s
      retries: 3
```

## Docker logs
```
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-customconfig: executing... 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/1) Installing mktorrent (1.1-r3)
Executing busybox-1.31.1-r19.trigger
OK: 200 MiB in 166 packages
[cont-init.d] 90-customconfig: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
