### ISSUE TITLE
nginx runs as root even with PUID and GPID set

### ISSUE THREAD

**Issue by BenoitAverty** [linuxserver/docker-rutorrent#56]
Hello,

I'm creating a service with this image with the following definition in a compose file : 
```
torrent:
    image: linuxserver/rutorrent
    environment:
      PUID: 9000
      PGID: 9000
      TZ: Europe/Paris
    volumes:
      - "/var/swarm-data/config/media-dl/torrent/:/config/"
      - "/var/download-data/work/torrent/:/downloads/"
    ports:
      - "80:80"
      - "5000:5000"
      - "51413:51413"
      - "6881:6881/udp"
```

And the problem is that nginx doesn't start because it's not able to create the log files. Error is the following : 
`nginx: [emerg] open() "/config/log/nginx/rutorrent.access.log" failed (13: Permission denied)`

I opened a terminal inside the container, and I've seen that the nginx process is started as root even though I defined PUID and PGID in the environment : 
```
abc@0890a13dd6c4:/config/log/nginx$ ps
PID   USER     TIME   COMMAND
    1 root       0:00 s6-svscan -t0 /var/run/s6/services
   29 root       0:00 s6-supervise s6-fdholderd
  227 root       0:00 s6-supervise nginx
  228 root       0:00 s6-supervise fpm
  229 root       0:00 s6-supervise rutorrent
  230 root       0:00 s6-supervise cron
  232 root       0:00 bash ./run
  234 root       0:00 bash ./run
  235 root       0:00 bash ./run
  241 root       0:00 /usr/sbin/crond -f -S -l 5 -c /etc/crontabs
  244 root       0:00 {php-fpm7} php-fpm: master process (/etc/php7/php-fpm.d/rutorrent.conf)
  257 abc        0:00 {php-fpm7} php-fpm: pool rutorrent
  258 abc        0:00 {php-fpm7} php-fpm: pool rutorrent
  270 root       0:00 tail -n 1 -f /config/log/rtorrent/rtorrent.log 269
 2532 abc        0:00 bash
 3117 abc        0:00 ps
```

To make it work, I removed the volume mounting of /config, so that there are no issues with the host filesystem. And sure enough, the nginx logs are created as root : 
```
root@da3b7604b643:/config/log/nginx$ ls -l
total 0
-rw-r--r-- 1 root root 0 Jun 16 15:53 rutorrent.access.log
-rw-r--r-- 1 root root 0 Jun 16 15:53 rutorrent.error.log
-rw-r--r-- 1 root root 0 Jun 16 15:53 rutorrent.rpc2.access.log
-rw-r--r-- 1 root root 0 Jun 16 15:53 rutorrent.rpc2.error.log
```

Since I don't care about the logs in this environment, I have a workaround which is to mount 4 volumes for folders that are not logs, and not mount the logs volume. But this is not optimal.

Thanks in advance
