### ISSUE TITLE
not gracefully exiting?

### ISSUE THREAD

**Issue by checktravis** [linuxserver/docker-rutorrent#77]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I am getting notifications from private trackers that I am running multiple sessions. I think this container isn't ending rtorrent sessions gracefully, but I can't find anything in the logs. 

I end with `docker-compose stop -t 120` (have also tried 500)

Is there anything else I can do to debug?	

Linux NUC 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

docker-compose up -d

```
version: '3'

services:

  rutorrent:
    restart: unless-stopped
    container_name: rutorrent
    image: linuxserver/rutorrent
    ports:
      - "80:80"
      - "5000:5000"
      - "65012:65012"
      - "6881:6881/udp"
    volumes:
      - /home/docman/rutorrent/data:/config
      - /home/docman/rutorrent/downloads:/downloads
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
```

```
rutorrent    |
rutorrent    | -------------------------------------
rutorrent    |           _         ()
rutorrent    |          | |  ___   _    __
rutorrent    |          | | / __| | |  /  \
rutorrent    |          | | \__ \ | | | () |
rutorrent    |          |_| |___/ |_|  \__/
rutorrent    |
rutorrent    |
rutorrent    | Brought to you by linuxserver.io
rutorrent    | We gratefully accept donations at:
rutorrent    | https://www.linuxserver.io/donations/
rutorrent    | -------------------------------------
rutorrent    | GID/UID
rutorrent    | -------------------------------------
rutorrent    |
rutorrent    | User uid:    1001
rutorrent    | User gid:    1001
rutorrent    | -------------------------------------
rutorrent    |
rutorrent    | [cont-init.d] 10-adduser: exited 0.
rutorrent    | [cont-init.d] 20-config: executing...
rutorrent    | [cont-init.d] 20-config: exited 0.
rutorrent    | [cont-init.d] done.
rutorrent    | [services.d] starting services
rutorrent    | [services.d] done.
rutorrent    | [cont-finish.d] executing container finish scripts...
rutorrent    | [cont-finish.d] done.
rutorrent    | [s6-finish] syncing disks.
rutorrent    | [s6-finish] sending all processes the TERM signal.
rutorrent    | [s6-finish] sending all processes the KILL signal and exiting.

```
