### ISSUE TITLE
All downloads stop running once rtorrent gets to around 100 torrents

### ISSUE THREAD

**Issue by khumps** [linuxserver/docker-rutorrent#78]
I am running into issues as I hit high numbers of torrents added concurrently. once I get near 100 all downloads just stop. They still say downloading but no bandwidth is leaving the machine. Restarting the container doesn't help but removing enough torrents gets it to resume.
	

 Ubuntu 17.10
 
```
version: '3.4'
services:

  nginx:
    image: nginx
    ports:
      - 80:80
      - 7878:7878
      - 8989:8989
      - 9117:9117
    networks:
      - default
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/htpasswd:/htpasswd
    restart: always

  openvpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: ${TZ}
    networks:
      - default
    dns:
      - 209.222.18.222
      - 209.222.18.218
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./openvpn:/vpn:ro
    restart: always

  rutorrent:
    image: linuxserver/rutorrent
    depends_on:
      - openvpn
    environment:
      TZ: ${TZ}
      PGID: 1000
      PUID: 1000
    network_mode: service:openvpn
    volumes:
      - ${RUTORRENT_CONFIG}:/config
      - ${RUTORRENT_DOWNLOADS_COMPLETE}:/downloads/complete
      - ${RUTORRENT_DOWNLOADS_INCOMPLETE}:/downloads/incomplete
      - ${RUTORRENT_DOWNLOADS_WATCH}:/downloads/watch
      - /media/PLEX:/media/PLEX
    restart: always

  jackett:
    image: linuxserver/jackett
    depends_on:
      - openvpn
    environment:
      TZ: ${TZ}
      PGID: 1000
      PUID: 1000
    network_mode: service:openvpn
    volumes:
      - ${JACKETT_CONFIG}:/config
      - ${JACKETT_DOWNLOADS}:/downloads
    restart: always

  radarr:
    image: linuxserver/radarr
    depends_on:
      - openvpn
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
    network_mode: service:openvpn
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${RADARR_DOWNLOADS}:/downloads
      - ${RADARR_MOVIES}:/movies
    restart: always

  sonarr:
    image: linuxserver/sonarr
    depends_on:
      - openvpn
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
    network_mode: service:openvpn
    volumes:
      - ${SONARR_CONFIG}:/config
      - ${SONARR_DOWNLOADS}:/downloads
      - ${SONARR_TV}:/tv
      - /media/PLEX/:/media/PLEX/
    restart: always

networks:
  default:
```

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
root@seedbox:/seedpot#
```

/media/PLEX is a mount.cifs share
