### ISSUE TITLE
XMLRPC errors when POSTing from Sonarr/Radarr

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-rutorrent#98]
When downloading through Sonarr and Radarr, I would observe that they fail. Looking through logs led me to messages like:

```
2018/12/29 07:59:08 [crit] 323#323: *1805 open() "/var/tmp/nginx/client_body/0000000602" failed (13: Permission denied), client: 172.19.0.2, server: _, request: "POST //php/addtorrent.php HTTP/1.1", host: ""
```

I found the way to fix this was to do `chmod go+w /var/tmp/nginx/client_body` in the container, but wonder if there's a better long-term fix.

**Comment by j0nnymoe** [comment]
Posting more information about your setup would be helpful as suggested by the issue template.

**Comment by ghost** [comment]
Running through a docker-compose file. Have it set up this way so that I can include radarr and sonarr in the same group. There's an nginx reverse proxy in there too. I use that so I can access the services without having to remember which port is what. The reverse proxy seems to be working fine; rtorrent seems to be working fine. Matter of fact, this all worked fine until I just did a `docker-compose pull` earlier today. Seems as though there were some changes made to this container in the last 30 days or so (since I last did the pull command).

The relevant portions of the compose file are:
```
  rtorrent:
    image: linuxserver/rutorrent
    container_name: rtorrent
    environment:
      PGID: 100
      PUID: 1029
    network_mode: "service:openvpn"
    volumes:
      - ./rtorrent:/config
      - ./downloads:/downloads
    restart: unless-stopped
    depends_on:
      - openvpn

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80/tcp"
      - "8443:443/tcp"
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
      - rtorrent
      - letsencrypt
```
